name: mosaique
channels:
  - conda-forge
  - defaults
dependencies:
  - boost-cpp=1.72.0=hdf9ef73_0
  - bzip2=1.0.8=h0b31af3_2
  - ca-certificates=2020.4.5.2=hecda079_0
  - cairo=1.16.0=hec6a9b0_1003
  - certifi=2020.4.5.2=py38h32f6830_0
  - cfitsio=3.470=hddc9c06_5
  - curl=7.69.1=h2d98d24_0
  - expat=2.2.9=h4a8c4bd_2
  - fontconfig=2.13.1=h6b1039f_1001
  - freetype=2.10.2=h8da9a1a_0
  - freexl=1.0.5=h1de35cc_1002
  - gdal=3.1.0=py38h9f7df5a_3
  - geos=3.8.1=h4a8c4bd_0
  - geotiff=1.6.0=hd8796ba_0
  - gettext=0.19.8.1=h46ab8bc_1002
  - giflib=5.2.1=h0b31af3_2
  - glib=2.64.3=h577aef8_0
  - hdf4=4.2.13=h84186c3_1003
  - hdf5=1.10.6=nompi_h3e39495_100
  - icu=64.2=h6de7cb9_1
  - jpeg=9d=h0b31af3_0
  - json-c=0.13.1=h575e443_1002
  - kealib=1.4.13=h40102fb_1
  - krb5=1.17.1=h1752a42_0
  - libblas=3.8.0=16_openblas
  - libcblas=3.8.0=16_openblas
  - libcurl=7.69.1=hc0b9707_0
  - libcxx=10.0.0=h1af66ff_2
  - libdap4=3.20.6=h8c15375_0
  - libedit=3.1.20191231=hed1e85f_0
  - libffi=3.2.1=h4a8c4bd_1007
  - libgdal=3.1.0=he0622db_3
  - libgfortran=4.0.0=2
  - libiconv=1.15=h0b31af3_1006
  - libkml=1.3.0=h169b8f9_1011
  - liblapack=3.8.0=16_openblas
  - libnetcdf=4.7.4=nompi_ha11d67f_104
  - libopenblas=0.3.10=h3d69b6c_0
  - libpng=1.6.37=hbbe82c9_1
  - libpq=12.2=h489d428_1
  - libspatialite=4.3.0a=h658e6c1_1038
  - libssh2=1.9.0=h39bdce6_2
  - libtiff=4.1.0=h2ae36a8_6
  - libwebp-base=1.1.0=h0b31af3_3
  - libxml2=2.9.10=h53d96d6_0
  - llvm-openmp=10.0.0=h28b9765_0
  - lz4-c=1.9.2=h4a8c4bd_1
  - ncurses=6.1=h0a44026_1002
  - numpy=1.18.5=py38h1f821a2_0
  - openjpeg=2.3.1=h254dc36_3
  - openssl=1.1.1g=h0b31af3_0
  - pcre=8.44=h4a8c4bd_0
  - pip=20.1.1=py_1
  - pixman=0.38.0=h01d97ff_1003
  - poppler=0.89.0=h3232a60_0
  - poppler-data=0.4.9=1
  - postgresql=12.2=h62ab893_1
  - proj=7.0.0=hbce2d5c_4
  - python=3.8.3=cpython_hd5f0129_0
  - python_abi=3.8=1_cp38
  - readline=8.0=hcfe32e1_0
  - setuptools=47.3.1=py38h32f6830_0
  - sqlite=3.30.1=h93121df_0
  - tbb=2019.9=ha1b3eb9_1
  - tiledb=2.0.5=h84aa2a7_0
  - tk=8.6.10=hbbe82c9_0
  - tzcode=2020a=h0b31af3_0
  - wheel=0.34.2=py_1
  - xerces-c=3.2.2=h8f8adb3_1004
  - xz=5.2.5=h0b31af3_0
  - zlib=1.2.11=h0b31af3_1006
  - zstd=1.4.4=h4b3e974_3
prefix: /anaconda2/envs/mosaique

